# Generated by Django 4.0 on 2024-02-13 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalenteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الإسم ثلاثي')),
                ('mobileNo', models.CharField(max_length=50, verbose_name='رقم الجوال')),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, null=True, verbose_name='نوع المستخدم')),
                ('bankName', models.CharField(max_length=80, verbose_name='إسم البنك :')),
                ('IBAN', models.CharField(max_length=80, verbose_name='IBAN :')),
                ('cardExpaiaryDate', models.CharField(max_length=80, verbose_name='cardExpaiaryDate :')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='المنطقة')),
                ('bioGraphy', models.CharField(blank=True, max_length=50, null=True, verbose_name='bioGraphy')),
                ('academicLevel', models.CharField(blank=True, max_length=50, null=True, verbose_name='academicLevel')),
                ('Certificates', models.CharField(blank=True, max_length=50, null=True, verbose_name='Certificates')),
                ('WorkField', models.CharField(blank=True, max_length=50, null=True, verbose_name='WorkField')),
                ('cv', models.FileField(blank=True, null=True, upload_to='', verbose_name='السيرة الذاتية :')),
                ('Dob', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dob :')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='Slug :')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='talenteUser')),
            ],
        ),
    ]
