# Generated by Django 4.2.11 on 2024-04-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_file_no_alter_profile_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='section',
            field=models.CharField(default=1, max_length=50, verbose_name='القسم :'),
            preserve_default=False,
        ),
    ]
